version: "3.8"

services:
  yolo_server:
    build:
      context: .
      dockerfile: dockerfile
    image: yolo_detection_server
    volumes:
      - ./:/yolov5-snap-go
    ports:
      - "8000:8000"
